### PR TITLE
Signing files with GPG

### PR DESCRIPTION
**Pull request by pospisilf**

### CODE REVIEW

**Review by djelinek — APPROVED** [review]
looks good to me, but the last word is on @apupier 🙂

**Review by apupier — APPROVED** [review]
- storing the asc file is only an intermediate iteration. When publish i implemented we will be able to not store it here, it will be pushed automatically to the Maven repository

**Comment by pospisilf** [comment]
> * storing the asc file is only an intermediate iteration. When publish i implemented we will be able to not store it here, it will be pushed automatically to the Maven repository

Agreed. I just wanted to be sure we have signed files. Do you want me to remove it right now or later?

**Comment by apupier** [comment]
> > * storing the asc file is only an intermediate iteration. When publish i implemented we will be able to not store it here, it will be pushed automatically to the Maven repository
> 
> Agreed. I just wanted to be sure we have signed files. Do you want me to remove it right now or later?

later when implementing the deploy to Maven repository is fine

**Comment by pospisilf** [comment]
> > > * storing the asc file is only an intermediate iteration. When publish i implemented we will be able to not store it here, it will be pushed automatically to the Maven repository
> > 
> > 
> > Agreed. I just wanted to be sure we have signed files. Do you want me to remove it right now or later?
> 
> later when implementing the deploy to Maven repository is fine

Ok, will merge this PR and close last issue.

**Pull request merged**
